import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './components/SessionProvider/Provider'
import ToasterContext from './components/ToasterContext/ToasterContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ETS Bot Pro',
  description: 'Generated by Express Tech Softwares',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Provider><ToasterContext />{children}</Provider></body>
    </html>
  )
}
